### ISSUE TITLE
师兄你好，接下来要将系统上线了

### ISSUE THREAD

**Issue by cai1818** [caojen/pgms-backend#3]
先前一直没用docker封装后端，现在要上传到学校服务器才用docker，但是前端就访问不了了
![ac4a8030769fcb9c1357ae0be162974](https://user-images.githubusercontent.com/72693103/198523700-23d0a924-fe1d-4880-b3af-bc84ca4ac85d.png)
一开始怀疑是dockerfile中密码有误，但改成123456，opentextfile+123456都不行。在生成镜像的时候有WARN
![ca5960ee258529b3eeff2e1787a379b](https://user-images.githubusercontent.com/72693103/198523912-c82dfc50-d549-4c4d-a861-52807b2f082e.png)

**Comment by caojen** [comment]
能不能定位到“数据库查询出错”的日志？最简单的方法是在query的try catch那里打个console.log

**Comment by cai1818** [comment]
在docker里怎么查看呢

**Comment by cai1818** [comment]
不使用docker是能正常使用的，因为之前没用docker

**Comment by cai1818** [comment]
![68ded2b631201a0408e5c8059063bb2](https://user-images.githubusercontent.com/72693103/198659002-01e77469-8b0f-49aa-84a9-73f92cde15c3.png)

**Comment by cai1818** [comment]
err内容

**Comment by cai1818** [comment]
感谢回复，找到问题了，没注意到dockerfile里的这个，换一下就好了docker.for.mac.host.internal
